version: '3.1'

services:
  app:
    image: strapi-app:latest
    build:
      context: .
      args:
        NODE_ENV: production
    restart: unless-stopped
    ports:
      - '${APP_PORT:-1337}:1337'
    environment:
      DATABASE_HOST: '${DATABASE_HOST:-db}'
      DATABASE_PORT: '${DATABASE_PORT:-3306}'
      DATABASE_USERNAME: '${DATABASE_USERNAME:-username}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD:-password}'
      DATABASE_NAME: '${DATABASE_NAME:-database}'

      HOST: '${STRAPI_HOST:-0.0.0.0}'
      PORT: '${STRAPI_PORT:-1337}'
      APP_KEYS: '${STRAPI_APP_KEYS:-toBeModified1,toBeModified2}'
      API_TOKEN_SALT: '${STRAPI_API_TOKEN_SALT:-tobemodified}'
      ADMIN_JWT_SECRET: '${STRAPI_ADMIN_JWT_SECRET:-tobemodified}'
      JWT_SECRET: '${STRAPI_JWT_SECRET:-tobemodified}'

  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME:-database}'
      MYSQL_USER: '${DATABASE_USERNAME:-username}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD:-password}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
